#!/usr/bin/env bash

set -e

if [ !`id rails 2> /dev/null` ]
then
  useradd -m rails -s /bin/bash
  su - rails <<-EOF
    set -e;
    mkdir -p ~/.ssh;
    chmod 700 ~/.ssh;
    touch ~/.ssh/authorized_keys;
    chmod 600 ~/.ssh/authorized_keys;
    echo $@ >> ~/.ssh/authorized_keys;
EOF
fi

