#!/usr/bin/env bash
# Usage: surf remote ruby

set -e

apt-get install -yfq libxslt1-dev libxml2-dev build-essential g++ ruby1.9.1-dev
# Install bundler if not installed
bundle -v 2>/dev/null || gem install bundler --no-rdoc --no-ri
