#!/usr/bin/env bash
set -e

if [ "$GIT_DIR" = "." ]; then
  cd ..
  unset GIT_DIR
fi


git reset --hard
git submodule init && git submodule sync && git submodule update

export RAILS_ENV=production
bundle install --deployment --without=development:test
./bin/rake db:migrate

# FIXME: this is broken when running w/ bundle --deployment
# bundle exec rake assets:precompile

git clean -x -f -- public/stylesheets public/javascripts

bundle exec pumactl -S ../puma restart

