#!/usr/bin/env bash
set -e

if [ "$GIT_DIR" = "." ]; then
  cd ..
  unset GIT_DIR
fi


git reset --hard
git submodule init && git submodule sync && git submodule update

export RAILS_ENV=production
bundle install --deployment --without=development:test
./bin/rake db:migrate

bundle exec rake assets:precompile
bundle exec rake assets:clean

bundle exec pumactl -S ../puma restart

