#!/usr/bin/env bash
# Usage: surf rails [ssh arguments]

set -e

ssh=${@:1}

surf remote "$ssh" apt-upgrade
surf remote "$ssh" nginx
surf remote "$ssh" postgresql
surf remote "$ssh" ruby
surf remote "$ssh" rails-user "`cat ~/.ssh/id_rsa.pub`"
#surf remote "$ssh" git-deploy
