#!/usr/bin/env bash
# Usage: surf remote url <remote-script> [arg1, arg2, ...]
# Help:
#   You can also send it commands on stdin:
#
#     surf remote url < script-to-run

set -e

url=$1

if [[ $url != *@* ]]; then
  url=root@$url
fi

if [ $2 ]; then
  ssh $url "bash -s ${@:3}" < $_SURF_ROOT/share/surf/remote/$2
else
  ssh $url "bash -s" <&0
fi
