#!/usr/bin/env bash
# Uage: surf puma <url>

set -e

if ! surf remote $1 <<< "status puma" > /dev/null 2>&1; then
  scp $_SURF_ROOT/share/surf/puma.conf root@$1:/etc/init/
  surf remote $1 <<< "stop puma > /dev/null 2>&1; start puma"
fi
