#!/usr/bin/env bash
# Usage: surf postgresql <url>

set -e

surf remote root@$1 apt-install postgresql libpq-dev
surf remote root@$1 <<-BASH
  set -e
  if ! sudo -u $2 psql $2 -tAc "SELECT 1" > /dev/null 2>&1; then
    cd /tmp
    sudo -u postgres createuser -D -R -S $2
    sudo -u postgres createdb --owner $2 --encoding utf8 $2
  fi
BASH
