#!/usr/bin/env bash
# Usage surf deploy <url> <name>

set -e

url=$1
name=$2

surf remote $url apt-install git

if ! git ls-remote $url > /dev/null 2>&1; then
  set +e
  git remote rm $url > /dev/null 2>&1
  set -e

  git remote add $url $name@$url:~/$name
  surf remote $name@$url <<-BASH
    set -e
    mkdir -p $name
    cd $name
    git init
    git config receive.denyCurrentBranch ignore
    mkdir -p config
BASH
  scp $_SURF_ROOT/share/surf/post-receive $name@$url:$name/.git/hooks/

  db=$TMPDIR/surf-database.yml-$$.$RANDOM
  sed s/{{name}}/$2/ $_SURF_ROOT/share/surf/database.yml > $db
  scp $db $name@$url:$name/config/database.yml
  
  git push $url master
fi
