#!/usr/bin/env bash
# Usage: surf nginx <url>

set -e

surf remote $1 apt-install nginx

if ! surf-remote root@$1 <<< "file /etc/nginx/sites-enabled/$2" > /dev/null 2>&1; then
  ngconf=$TMPDIR/surf-nginx.conf-$$.$RANDOM
  sed s/{{name}}/$2/g $_SURF_ROOT/share/surf/nginx.conf |
  sed s/{{url}}/$1/g  > $ngconf 

  scp $ngconf root@$1:/etc/nginx/sites-available/$2

  surf remote root@$1 <<-BASH
    set -e
    rm -f /etc/nginx/sites-enabled/default
    ln -sf /etc/nginx/sites-available/$2 /etc/nginx/sites-enabled/
    service nginx start
BASH
fi
